# Generated by Django 4.1.7 on 2023-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('transaction_time', models.TimeField(verbose_name='Transaction Time')),
                ('from_acct', models.IntegerField(verbose_name='Sending Account ID')),
                ('from_name', models.CharField(max_length=50, verbose_name='Sending AccountName')),
                ('from_no', models.IntegerField(verbose_name='Sending Phone Number')),
                ('trans_type', models.CharField(max_length=50, verbose_name='Transaction Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('fees', models.IntegerField(verbose_name='Fees')),
                ('ba_before', models.IntegerField(verbose_name='Balance Before')),
                ('bal_after', models.IntegerField(verbose_name='Balance After')),
                ('to_no', models.IntegerField(verbose_name='Receiving PhoneNumber')),
                ('to_name', models.CharField(max_length=50, verbose_name='Receiving AccountName')),
                ('to_acct', models.IntegerField(verbose_name='Receiving PhoneNumber')),
                ('f_id', models.IntegerField(verbose_name='Transaction ID')),
                ('ref', models.CharField(max_length=50, verbose_name='Reference')),
                ('ova', models.CharField(max_length=50, verbose_name='Online Vendor Account')),
            ],
        ),
    ]
