# Generated by Django 4.1.3 on 2023-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_transactions_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscore',
            name='agent_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='eligibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
