# Generated by Django 4.1.7 on 2023-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_activity', models.IntegerField()),
                ('freq_of_rebal', models.IntegerField()),
                ('mode_cash_in', models.IntegerField()),
                ('median_cash_in', models.IntegerField()),
                ('mode_cash_out', models.IntegerField()),
                ('median_cash_out', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('len_of_serve_score', models.IntegerField(blank=True, null=True)),
                ('freq_act_score', models.IntegerField(blank=True, null=True)),
                ('freq_rebal_score', models.IntegerField(blank=True, null=True)),
                ('mode_cash_in_score', models.IntegerField(blank=True, null=True)),
                ('median_cash_in_score', models.IntegerField(blank=True, null=True)),
                ('mode_cash_out_score', models.IntegerField(blank=True, null=True)),
                ('median_cash_out_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='ref',
            field=models.CharField(blank=True, max_length=50, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='to_acct',
            field=models.CharField(blank=True, max_length=50, verbose_name='Receiving PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transaction Date'),
        ),
    ]
