# Generated by Django 4.1.3 on 2023-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_creditscore_agent_name_creditscore_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditscore',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agent Name'),
        ),
    ]
